//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TyrannosaurusPlex.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class DB : global::System.Configuration.ApplicationSettingsBase {
        
        private static DB defaultInstance = ((DB)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DB())));
        
        public static DB Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string HOST {
            get {
                return ((string)(this["HOST"]));
            }
            set {
                this["HOST"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("t_plex_db")]
        public string DATABASE {
            get {
                return ((string)(this["DATABASE"]));
            }
            set {
                this["DATABASE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root")]
        public string USER {
            get {
                return ((string)(this["USER"]));
            }
            set {
                this["USER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1328259")]
        public string PASSWORD {
            get {
                return ((string)(this["PASSWORD"]));
            }
            set {
                this["PASSWORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("recipes")]
        public string RECIPE_TABLE {
            get {
                return ((string)(this["RECIPE_TABLE"]));
            }
            set {
                this["RECIPE_TABLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("id,part_number,checksheet_type,key_sequence,csv_location,timestamp_col,a_col,b_co" +
            "l,c_col,d_col,e_col,f_col,g_col,h_col,i_col,j_col,k_col,l_col,m_col")]
        public string RECIPE_TABLE_COLUMN_SCHEMA {
            get {
                return ((string)(this["RECIPE_TABLE_COLUMN_SCHEMA"]));
            }
            set {
                this["RECIPE_TABLE_COLUMN_SCHEMA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("checksheet_types")]
        public string CHECKSHEET_TABLE {
            get {
                return ((string)(this["CHECKSHEET_TABLE"]));
            }
            set {
                this["CHECKSHEET_TABLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sheet_type")]
        public string CHECKSHEET_TABLE_COLUMN_SCHEMA {
            get {
                return ((string)(this["CHECKSHEET_TABLE_COLUMN_SCHEMA"]));
            }
            set {
                this["CHECKSHEET_TABLE_COLUMN_SCHEMA"] = value;
            }
        }
    }
}
